// Generated by Selenium IDE

using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
using OpenQA.Selenium.Support.Extensions;

[TestFixture]
public class TauthTest
{
    private IWebDriver driver;
    public IDictionary<string, object> vars { get; private set; }
    private IJavaScriptExecutor js;

    [SetUp]
    public void SetUp()
    {
        driver = new FirefoxDriver();
        js = (IJavaScriptExecutor)driver;
        vars = new Dictionary<string, object>();
    }

    [TearDown]
    protected void TearDown()
    {
        driver.Quit();
    }

    [Test]
    public void tauth()
    {
        driver.Navigate().GoToUrl("https://www.reddit.com/");
        driver.Manage().Window.Size = new System.Drawing.Size(1292, 812);
        driver.FindElement(By.CssSelector("#login-button > .flex > .flex")).Click();
        {
            var element = driver.FindElement(By.Id("login-button"));
            Actions builder = new Actions(driver);
            builder.MoveToElement(element).Perform();
        }
        {
            var element = driver.FindElement(By.CssSelector(".mr-md:nth-child(3) .h-\\[185px\\]"));
            Actions builder = new Actions(driver);
            builder.MoveToElement(element).Perform();
        }
        {
            var element = driver.FindElement(By.TagName("body"));
            Actions builder = new Actions(driver);
            builder.MoveToElement(element, 0, 0).Perform();
        }
        var loginElement = driver.FindElement(By.Id("login-username"));
        driver.ExecuteJavaScript("arguments[0].value = 'klimkin_ilya2004@mail.ru';", loginElement);
        
        var passwordElement = driver.FindElement(By.Id("login-password"));
        driver.ExecuteJavaScript("arguments[0].value = 'HG2004klmkn';", passwordElement);

        new Actions(driver).SendKeys(Keys.Enter).Perform();
    }
}