// Generated by Selenium IDE

using TestAuth2._2.Models;

namespace TestAuth2._2;

[TestFixture]
public class TestAuth : TestBase
{
    [Test]
    public void tauth()
    {
        var userData = new UserData("klimkin_ilya2004@mail.ru", "HG2004klmkn");
        var postData = new PostData("Пример заголовка", "Привет это пример текста");

        OpenHomePage();
        Login(userData);
        CreateDraft(postData);
    }
}